"use client";

import React from "react";
import Link from "next/link";
import { motion } from "framer-motion";
import { Navbar } from "@/components/navbar/Navbar";
import { Footer } from "@/components/layout/Footer";
import { Fingerprint, ShieldAlert, FileText, Settings, ShieldCheck, Eye } from "lucide-react";
import { HeroTypeLine } from "@/components/ui/HeroTypeLine";
import { CyberSectionDivider } from "@/components/ui/CyberSectionDivider";
import { InteractiveProcessSection } from "@/components/ui/InteractiveProcessSection";
import { DEFCTASection } from "@/app/services/defensive-security/soc-management/DEFCTASection";
import { Breadcrumbs } from "@/components/ui/Breadcrumbs";
import { HeroSection } from "./sections/HeroSection";

const steps = [
  {
    id: "assess",
    title: "KYC Channel Robustness Assessment",
    description: "We evaluate your online identity verification procedures, biometric controls, and passive/active liveness check solutions.",
    icon: <Settings className="w-8 h-8 text-white" />
  },
  {
    id: "simulate",
    title: "Deepfake Attack Simulations",
    description: "Our engineers simulate real-time attacks using voice clones of your executives or synthetic faces generated by GANs to attempt bypassing your controls.",
    icon: <ShieldAlert className="w-8 h-8 text-white" />
  },
  {
    id: "analyze",
    title: "Advanced Media Forensics",
    description: "We deploy forensic analysis engines to detect voice frequency anomalies, unnatural blinking patterns, and skin texture inconsistencies.",
    icon: <Eye className="w-8 h-8 text-white" />
  },
  {
    id: "harden",
    title: "Biometric & Liveness Hardening",
    description: "We integrate multi-frame active/passive liveness detection controls and fortify KYC pipelines against real-time generative AI tools.",
    icon: <ShieldCheck className="w-8 h-8 text-white" />
  },
  {
    id: "report",
    title: "Synthetic Fraud Mitigation Plan",
    description: "Delivery of a technical report and actionable operational guidelines to immunize support and validation teams against AI-driven social engineering.",
    icon: <FileText className="w-8 h-8 text-white" />
  }
];

export default function DeepfakeIdentityDetectionPage() {
  return (
    <main className="flex min-h-screen flex-col bg-white">
      <Navbar />
      <HeroSection />
      <CyberSectionDivider theme="red" />

      {/* Interactive Process Section */}
      <InteractiveProcessSection
        title="Biometric Validation Methodology"
        description="A comprehensive protocol to immunize your authentication pipelines against synthetic fraud."
        steps={steps}
      />

      <CyberSectionDivider theme="red" />

      {/* Fraud Vectors Analyzed */}
      <motion.section initial={{ opacity: 0, y: 40 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: 0.1 }} transition={{ duration: 0.8 }} className="py-24 bg-zinc-50 border-b border-zinc-200">
        <div className="container mx-auto px-6">
          <div className="mb-16 text-center max-w-3xl mx-auto">
            <h2 className="text-red-600 font-bold text-sm tracking-widest uppercase mb-4 flex items-center justify-center gap-4">
              <span className="w-8 h-px bg-red-600/30"></span>
              Emerging Threats
              <span className="w-8 h-px bg-red-600/30"></span>
            </h2>
            <h2 className="text-3xl lg:text-5xl font-black tracking-tight text-zinc-900 mb-6">
              Synthetic Identity Fraud Vectors
            </h2>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            <div className="bg-white p-8 rounded-2xl shadow-xl border border-zinc-100">
              <div className="w-12 h-12 rounded-xl bg-red-50 text-red-600 flex items-center justify-center mb-6">
                <ShieldAlert className="w-6 h-6" />
              </div>
              <h3 className="text-xl font-bold text-zinc-900 mb-4">Real-Time Voice Cloning</h3>
              <p className="text-zinc-600 text-sm leading-relaxed">
                Defeat sophisticated BEC (Business Email Compromise) schemes where attackers leverage short audio samples to perfectly clone executive voice prints during urgent calls.
              </p>
            </div>

            <div className="bg-white p-8 rounded-2xl shadow-xl border border-zinc-100">
              <div className="w-12 h-12 rounded-xl bg-red-50 text-red-600 flex items-center justify-center mb-6">
                <Fingerprint className="w-6 h-6" />
              </div>
              <h3 className="text-xl font-bold text-zinc-900 mb-4">KYC Liveness Bypasses</h3>
              <p className="text-zinc-600 text-sm leading-relaxed">
                Prevent malicious actors from opening fraudulent bank accounts or bypassing identity screens using real-time face-swap software hooked to virtual cameras.
              </p>
            </div>

            <div className="bg-white p-8 rounded-2xl shadow-xl border border-zinc-100">
              <div className="w-12 h-12 rounded-xl bg-red-50 text-red-600 flex items-center justify-center mb-6">
                <Eye className="w-6 h-6" />
              </div>
              <h3 className="text-xl font-bold text-zinc-900 mb-4">Video Social Engineering</h3>
              <p className="text-zinc-600 text-sm leading-relaxed">
                Educate and secure your staff against fake Teams or Zoom meetings where attackers display dynamic synthetic avatars of colleagues to request financial transfers.
              </p>
            </div>
          </div>
        </div>
      </motion.section>

      <CyberSectionDivider theme="red" />

      <DEFCTASection />

      <Footer />
    </main>
  );
}
