"use client";

import React from "react";
import Link from "next/link";
import { motion } from "framer-motion";
import { Navbar } from "@/components/navbar/Navbar";
import { Footer } from "@/components/layout/Footer";
import { Fingerprint, ShieldAlert, FileText, Settings, ShieldCheck, Eye } from "lucide-react";
import { HeroTypeLine } from "@/components/ui/HeroTypeLine";
import { CyberSectionDivider } from "@/components/ui/CyberSectionDivider";
import { InteractiveProcessSection } from "@/components/ui/InteractiveProcessSection";
import { DEFCTASection } from "../../defensive-security/soc-management/DEFCTASection";

const steps = [
  {
    id: "assess",
    title: "KYC Channel Robustness Audit",
    description: "We evaluate your online identity verification procedures, biometric controls, and passive/active liveness check solutions.",
    icon: <Settings className="w-8 h-8 text-white" />
  },
  {
    id: "simulate",
    title: "Deepfake Attack Simulations",
    description: "Our engineers simulate real-time attacks using voice clones of your executives or synthetic faces generated by GANs to attempt bypassing your controls.",
    icon: <ShieldAlert className="w-8 h-8 text-white" />
  },
  {
    id: "analyze",
    title: "Advanced Media Forensics",
    description: "We deploy forensic analysis engines to detect voice frequency anomalies, unnatural blinking patterns, and skin texture inconsistencies.",
    icon: <Eye className="w-8 h-8 text-white" />
  },
  {
    id: "harden",
    title: "Biometric & Liveness Hardening",
    description: "We integrate multi-frame active/passive liveness detection controls and fortify KYC pipelines against real-time generative AI tools.",
    icon: <ShieldCheck className="w-8 h-8 text-white" />
  },
  {
    id: "report",
    title: "Synthetic Fraud Mitigation Plan",
    description: "Delivery of a technical report and actionable operational guidelines to immunize support and validation teams against AI-driven social engineering.",
    icon: <FileText className="w-8 h-8 text-white" />
  }
];

export default function DeepfakeIdentityDetectionPage() {
  return (
    <main className="flex min-h-screen flex-col bg-white">
      <Navbar />

      {/* Hero Section */}
      <motion.section initial={{ opacity: 0, y: 40 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: 0.1 }} transition={{ duration: 0.8 }} className="relative bg-zinc-950 pt-32 pb-20 lg:pt-48 lg:pb-32 overflow-hidden">
        <div className="absolute inset-0 z-0 opacity-40 pointer-events-none">
          <video
            autoPlay
            loop
            muted
            playsInline
            className="absolute inset-0 w-full h-full object-cover object-center"
          >
            <source src="/vids/videoplayback.mp4" type="video/mp4" />
          </video>
        </div>
        <div className="absolute inset-0 bg-black/40 sm:bg-linear-to-r sm:from-black/85 sm:via-black/45 sm:to-transparent pointer-events-none" />

        <div className="container mx-auto px-6 relative z-10">
          <div className="flex flex-col lg:flex-row items-center gap-16">
            <div className="lg:w-1/2">
              <motion.div
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.5 }}
                className="inline-flex items-center flex-wrap gap-2 text-red-400 mb-6"
              >
                <span className="w-2 h-2 rounded-full bg-red-500 animate-pulse shrink-0" />
                <div className="flex flex-wrap items-center gap-2 text-sm font-semibold tracking-wide uppercase">
                  <Link href="/services" className="hover:text-red-300 transition-colors">Services</Link>
                  <span className="text-red-500/30 flex flex-nowrap shrink-0">/</span>
                  <Link href="/services/ai-cybersecurity" className="hover:text-red-300 transition-colors break-keep">AI & Cybersecurity</Link>
                  <span className="text-red-500/30 flex flex-nowrap shrink-0">/</span>
                  <span className="text-white/90">Deepfake Detection</span>
                </div>
              </motion.div>

              <h1 className="text-4xl md:text-5xl lg:text-6xl font-bold text-white leading-tight mb-6">
                Deepfake <span className="text-transparent bg-clip-text bg-gradient-to-r from-red-500 to-red-700">Detection</span>
              </h1>

              <HeroTypeLine
                items={["Voice and face clone detection", "Biometric KYC pipeline protection", "Synthetic media forensics"]}
              />

              <p className="text-lg text-zinc-400 mb-8 leading-relaxed max-w-xl">
                Protect your identity verification pipelines and critical communications against highly sophisticated real-time synthetic identity fraud and deepfakes.
              </p>

              <div className="flex flex-wrap items-center gap-4">
                <Link href="/contact" className="px-8 py-3.5 bg-red-600 text-white font-medium rounded-lg hover:bg-red-700 transition-all duration-300 shadow-lg shadow-red-600/25">
                  Audit Your KYC Process
                </Link>
              </div>
            </div>

            <div className="lg:w-1/2 relative hidden lg:block">
              <div className="absolute inset-0 bg-gradient-to-tr from-red-500/10 to-transparent blur-3xl rounded-full" />
              <div className="relative rounded-2xl overflow-hidden border border-zinc-800 shadow-2xl p-2 bg-zinc-900/50 backdrop-blur-md">
                <img src="https://images.unsplash.com/photo-1509062522246-3755977927d7?q=80&w=1200&auto=format&fit=crop" alt="Deepfake & Deep Identity Detection" className="rounded-xl w-full object-cover h-[350px] opacity-80" />
              </div>
            </div>
          </div>
        </div>
      </motion.section>

      <CyberSectionDivider theme="red" />

      {/* Interactive Process Section */}
      <InteractiveProcessSection
        title="Biometric Validation Methodology"
        description="A comprehensive protocol to immunize your authentication pipelines against synthetic fraud."
        steps={steps}
      />

      <CyberSectionDivider theme="red" />

      {/* Fraud Vectors Analyzed */}
      <motion.section initial={{ opacity: 0, y: 40 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: 0.1 }} transition={{ duration: 0.8 }} className="py-24 bg-zinc-50 border-b border-zinc-200">
        <div className="container mx-auto px-6">
          <div className="mb-16 text-center max-w-3xl mx-auto">
            <h2 className="text-red-600 font-bold text-sm tracking-widest uppercase mb-4 flex items-center justify-center gap-4">
              <span className="w-8 h-px bg-red-600/30"></span>
              Emerging Threats
              <span className="w-8 h-px bg-red-600/30"></span>
            </h2>
            <h2 className="text-3xl lg:text-5xl font-black tracking-tight text-zinc-900 mb-6">
              Synthetic Identity Fraud Vectors
            </h2>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            <div className="bg-white p-8 rounded-2xl shadow-xl border border-zinc-100">
              <div className="w-12 h-12 rounded-xl bg-red-50 text-red-600 flex items-center justify-center mb-6">
                <ShieldAlert className="w-6 h-6" />
              </div>
              <h3 className="text-xl font-bold text-zinc-900 mb-4">Real-Time Voice Cloning</h3>
              <p className="text-zinc-600 text-sm leading-relaxed">
                Defeat sophisticated BEC (Business Email Compromise) schemes where attackers leverage short audio samples to perfectly clone executive voice prints during urgent calls.
              </p>
            </div>

            <div className="bg-white p-8 rounded-2xl shadow-xl border border-zinc-100">
              <div className="w-12 h-12 rounded-xl bg-red-50 text-red-600 flex items-center justify-center mb-6">
                <Fingerprint className="w-6 h-6" />
              </div>
              <h3 className="text-xl font-bold text-zinc-900 mb-4">KYC Liveness Bypasses</h3>
              <p className="text-zinc-600 text-sm leading-relaxed">
                Prevent malicious actors from opening fraudulent bank accounts or bypassing identity screens using real-time face-swap software hooked to virtual cameras.
              </p>
            </div>

            <div className="bg-white p-8 rounded-2xl shadow-xl border border-zinc-100">
              <div className="w-12 h-12 rounded-xl bg-red-50 text-red-600 flex items-center justify-center mb-6">
                <Eye className="w-6 h-6" />
              </div>
              <h3 className="text-xl font-bold text-zinc-900 mb-4">Video Social Engineering</h3>
              <p className="text-zinc-600 text-sm leading-relaxed">
                Educate and secure your staff against fake Teams or Zoom meetings where attackers display dynamic synthetic avatars of colleagues to request financial transfers.
              </p>
            </div>
          </div>
        </div>
      </motion.section>

      <CyberSectionDivider theme="red" />

      <DEFCTASection />

      <Footer />
    </main>
  );
}
