"use client";

import React, { useState } from "react";
import Link from "next/link";
import { motion } from "framer-motion";
import { Navbar } from "@/components/navbar/Navbar";
import { Footer } from "@/components/layout/Footer";
import {
  ArrowRight,
  CheckCircle2,
  BrainCircuit,
  Bot,
  Radar,
  ShieldAlert,
  Fingerprint,
  Lock,
  Zap,
  Cpu,
  ShieldCheck
} from "lucide-react";
import { HeroTypeLine } from "@/components/ui/HeroTypeLine";
import { CyberSectionDivider } from "@/components/ui/CyberSectionDivider";
import { DEFCTASection } from "../defensive-security/soc-management/DEFCTASection";

const offerings = [
  {
    title: "LLM Security Assessment",
    desc: "Rigorous penetration testing of your large language models to identify prompt injection, training data leakage, and jailbreaking vulnerabilities.",
    icon: <Bot className="w-8 h-8" />,
    threats: ["Prompt Injection", "Training data leakage"],
    features: ["Model Sandboxing", "Input sanitation"],
    href: "/services/ai-cybersecurity/llm-security-assessment",
  },
  {
    title: "AI-Powered Threat Detection",
    desc: "Implementation of advanced machine learning algorithms to detect traffic anomalies, behavioral deviations, and zero-day attacks in real time.",
    icon: <Radar className="w-8 h-8" />,
    threats: ["Zero-Day Exploits", "Advanced persistent threats"],
    features: ["Behavioral analysis", "Automated threat hunting"],
    href: "/services/ai-cybersecurity/ai-powered-threat-detection",
  },
  {
    title: "Adversarial Machine Learning Defense",
    desc: "Protection of your classification and prediction models against adversarial attacks seeking to deceive or poison artificial intelligence.",
    icon: <ShieldAlert className="w-8 h-8" />,
    threats: ["Data poisoning", "Evasion attacks"],
    features: ["Robust training", "Robustness validation"],
    href: "/services/ai-cybersecurity/adversarial-ml-defense",
  },
  {
    title: "Generative AI Governance",
    desc: "Establishment of governance and compliance frameworks for secure and ethical adoption of generative AI within your enterprise, aligned with the EU AI Act.",
    icon: <BrainCircuit className="w-8 h-8" />,
    threats: ["Regulatory non-compliance", "Unregulated AI usage"],
    features: ["AI charter creation", "Ethical & technical audits"],
    href: "/services/ai-cybersecurity/generative-ai-governance",
  },
  {
    title: "Deepfake & Synthetic Identity Detection",
    desc: "Usage of cutting-edge AI tools to verify digital identities and detect voice clones or synthesized videos generated by AI (Deepfakes).",
    icon: <Fingerprint className="w-8 h-8" />,
    threats: ["Identity theft", "Advanced social engineering"],
    features: ["Biometric validation", "Synthetic media detection"],
    href: "/services/ai-cybersecurity/deepfake-identity-detection",
  },
];

const benefits = [
  {
    title: "Ultra-Fast Speed and Scale",
    desc: "AI enables processing of millions of security events per microsecond, identifying correlations invisible to a human eye.",
    icon: <Zap className="w-5 h-5" />
  },
  {
    title: "Resilience to Zero-Day Threats",
    desc: "By analyzing behavioral drift rather than simple file signatures, we block previously unseen and unrecorded attacks.",
    icon: <ShieldCheck className="w-5 h-5" />
  },
  {
    title: "Reduction of Analyst Alert Fatigue",
    desc: "Intelligent automation filters and correlates low-value SOC alerts, freeing your experts to focus on active threat hunting.",
    icon: <Cpu className="w-5 h-5" />
  },
  {
    title: "Immunity of Your AI Systems",
    desc: "Secure your machine learning models against malicious exploitation, guaranteeing the integrity of your predictions and decisions.",
    icon: <Lock className="w-5 h-5" />
  }
];

export default function AICybersecurityLandingPage() {
  const [activeIdx, setActiveIdx] = useState(0);

  return (
    <main className="flex min-h-screen flex-col bg-white">
      <Navbar />

      {/* Hero Section */}
      <motion.section initial={{ opacity: 0, y: 40 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: 0.1 }} transition={{ duration: 0.8 }} className="relative bg-zinc-950 pt-32 pb-20 lg:pt-48 lg:pb-32 overflow-hidden">
        <div className="absolute inset-0 z-0 opacity-40 pointer-events-none">
          <video
            autoPlay
            loop
            muted
            playsInline
            className="absolute inset-0 w-full h-full object-cover object-center"
          >
            <source src="/vids/videoplayback.mp4" type="video/mp4" />
          </video>
        </div>
        <div className="absolute inset-0 bg-black/40 sm:bg-linear-to-r sm:from-black/85 sm:via-black/45 sm:to-transparent pointer-events-none" />

        <div className="container mx-auto px-6 relative z-10">
          <div className="max-w-3xl">
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.5 }}
              className="inline-flex items-center flex-wrap gap-2 text-red-400 mb-6"
            >
              <span className="w-2 h-2 rounded-full bg-red-500 animate-pulse shrink-0" />
              <div className="flex flex-wrap items-center gap-2 text-sm font-semibold tracking-wide uppercase">
                <Link href="/services" className="hover:text-red-300 transition-colors">Services</Link>
                <span className="text-red-500/30 flex flex-nowrap shrink-0">/</span>
                <span className="text-white/90">AI & Cybersecurity</span>
              </div>
            </motion.div>

            <h1 className="text-4xl md:text-5xl lg:text-7xl font-bold text-white leading-tight mb-6">
              AI & <span className="text-transparent bg-clip-text bg-gradient-to-r from-red-500 to-red-700">Cybersecurity</span>
            </h1>

            <HeroTypeLine
              items={["Securing LLMs and Generative AI", "Intelligent threat detection", "Defending against adversarial ML"]}
            />

            <p className="text-lg text-zinc-400 mb-8 leading-relaxed max-w-2xl">
              As Artificial Intelligence deeply transforms the corporate landscape, protecting your models from malicious exploitation becomes critical. Keystone delivers advanced security audits for your AI systems and deploys intelligent defenses to immunize your future operations.
            </p>

            <div className="flex flex-wrap items-center gap-4">
              <Link href="/contact" className="px-8 py-3.5 bg-red-600 text-white font-medium rounded-lg hover:bg-red-700 transition-all duration-300 shadow-lg shadow-red-600/25">
                Protect Your AI Systems
              </Link>
            </div>
          </div>
        </div>
      </motion.section>

      <CyberSectionDivider theme="red" />

      {/* Approach Section */}
      <motion.section initial={{ opacity: 0, y: 40 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: 0.1 }} transition={{ duration: 0.8 }} className="py-24 bg-white text-zinc-900">
        <div className="container mx-auto px-6">
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-16 items-center">
            <div>
              <h2 className="text-red-600 font-bold text-sm tracking-widest uppercase mb-4 flex items-center gap-4">
                <span className="w-8 h-px bg-red-600/30"></span>
                Our Approach
              </h2>
              <h2 className="text-3xl lg:text-5xl font-black tracking-tight text-zinc-900 mb-6">
                AI and Cybersecurity: Dual Perspective
              </h2>
              <p className="text-zinc-600 text-lg mb-6 leading-relaxed">
                At Keystone, we believe that modern cybersecurity requires addressing AI from two complementary and strategic angles.
              </p>
              <div className="space-y-6">
                <div className="flex gap-4">
                  <div className="w-12 h-12 rounded-xl bg-red-50 text-red-600 flex items-center justify-center shrink-0">
                    <Lock className="w-6 h-6" />
                  </div>
                  <div>
                    <h3 className="text-lg font-bold text-zinc-900 mb-2">1. Securing AI</h3>
                    <p className="text-zinc-600 text-sm leading-relaxed">
                      Your AI models (LLMs, predictive pipelines) process highly sensitive data. We audit them to block prompt injections, behavioral evasion, model extraction, and training dataset poisoning.
                    </p>
                  </div>
                </div>
                <div className="flex gap-4">
                  <div className="w-12 h-12 rounded-xl bg-zinc-900 text-white flex items-center justify-center shrink-0">
                    <BrainCircuit className="w-6 h-6" />
                  </div>
                  <div>
                    <h3 className="text-lg font-bold text-zinc-900 mb-2">2. AI for Security</h3>
                    <p className="text-zinc-600 text-sm leading-relaxed">
                      Traditional threats evolve too rapidly. We leverage machine learning models to analyze user behavior, pinpoint microsecond network anomalies, and proactively neutralize zero-day exploits.
                    </p>
                  </div>
                </div>
              </div>
            </div>
            <div className="relative">
              <div className="absolute inset-0 bg-gradient-to-tr from-red-500/10 to-transparent blur-3xl rounded-full" />
              <div className="relative rounded-2xl overflow-hidden border border-zinc-100 shadow-2xl p-4 bg-zinc-50">
                <img src="https://images.unsplash.com/photo-1677442136019-21780efad99a?q=80&w=1200&auto=format&fit=crop" alt="AI & Cybersecurity" className="rounded-xl w-full object-cover h-[450px]" />
              </div>
            </div>
          </div>
        </div>
      </motion.section>

      <CyberSectionDivider theme="red" />

      {/* Offerings Grid */}
      <motion.section initial={{ opacity: 0, y: 40 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: 0.1 }} transition={{ duration: 0.8 }} className="py-24 bg-zinc-50 border-b border-zinc-200">
        <div className="container mx-auto px-6">
          <div className="mb-16 text-center max-w-3xl mx-auto">
            <h2 className="text-red-600 font-bold text-sm tracking-widest uppercase mb-4 flex items-center justify-center gap-4">
              <span className="w-8 h-px bg-red-600/30"></span>
              AI Technological Capabilities
              <span className="w-8 h-px bg-red-600/30"></span>
            </h2>
            <h2 className="text-3xl lg:text-5xl font-black tracking-tight text-zinc-900 mb-6">
              Our Specialized Services
            </h2>
            <p className="text-zinc-600 text-lg">
              From robustness analysis of your language models to advanced identity fraud detection through Deepfake analysis, explore our complete range of secure AI services.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8 justify-center">
            {offerings.map((offer, idx) => (
              <motion.div
                key={idx}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true, margin: "-50px" }}
                transition={{ delay: idx * 0.05, duration: 0.6 }}
                whileHover={{ y: -5 }}
                className="bg-white rounded-2xl p-8 shadow-xl border border-zinc-100 flex flex-col h-full hover:shadow-2xl transition-all duration-300"
              >
                <div className="text-red-600 bg-red-50 p-3.5 rounded-xl w-fit mb-6">
                  {offer.icon}
                </div>

                <h3 className="text-xl font-bold text-zinc-900 mb-3" dangerouslySetInnerHTML={{ __html: offer.title }} />

                <p className="text-zinc-600 text-sm leading-relaxed flex-grow mb-6" dangerouslySetInnerHTML={{ __html: offer.desc }} />

                <div className="grid grid-cols-2 gap-4 border-t border-zinc-100 pt-6 mb-6">
                  <div>
                    <h4 className="text-[10px] font-bold text-zinc-400 uppercase tracking-wider mb-2 flex items-center gap-2">
                      <Radar className="w-3.5 h-3.5 text-zinc-400" /> Risks
                    </h4>
                    <ul className="space-y-1">
                      {offer.threats.map((t, i) => (
                        <li key={i} className="text-xs text-zinc-500 flex items-center gap-1.5">
                          <span className="w-1 h-1 rounded-full bg-zinc-300" />
                          {t}
                        </li>
                      ))}
                    </ul>
                  </div>
                  <div>
                    <h4 className="text-[10px] font-bold text-zinc-400 uppercase tracking-wider mb-2 flex items-center gap-2">
                      <CheckCircle2 className="w-3.5 h-3.5 text-red-500" /> Focus
                    </h4>
                    <ul className="space-y-1">
                      {offer.features.map((f, i) => (
                        <li key={i} className="text-xs text-zinc-500 flex items-center gap-1.5">
                          <span className="w-1.5 h-1.5 rounded-full bg-red-400" />
                          {f}
                        </li>
                      ))}
                    </ul>
                  </div>
                </div>

                <Link
                  href={offer.href}
                  className="inline-flex w-fit items-center gap-2 text-sm font-bold text-red-600 hover:text-red-700 transition-colors"
                >
                  Discover the solution
                  <ArrowRight className="w-4 h-4" />
                </Link>
              </motion.div>
            ))}
          </div>
        </div>
      </motion.section>

      <CyberSectionDivider theme="red" />

      {/* Why Keystone Benefits Section */}
      <motion.section initial={{ opacity: 0, y: 40 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: 0.1 }} transition={{ duration: 0.8 }} className="py-24 bg-white text-zinc-900">
        <div className="container mx-auto px-6">
          <div className="text-center max-w-3xl mx-auto mb-20">
            <h2 className="text-red-600 font-bold text-sm tracking-widest uppercase mb-4 flex items-center justify-center gap-4">
              <span className="w-8 h-px bg-red-600/30"></span>
              AI Benefits
              <span className="w-8 h-px bg-red-600/30"></span>
            </h2>
            <h2 className="text-3xl lg:text-5xl font-black tracking-tight text-zinc-900 mb-6">
              Why Associate AI with Your Security?
            </h2>
          </div>

          <div className="flex flex-col lg:flex-row gap-16 items-center">
            <div className="w-full lg:w-1/2 flex flex-col gap-4">
              {benefits.map((b, idx) => (
                <button
                  key={idx}
                  onClick={() => setActiveIdx(idx)}
                  className={`group text-left p-6 rounded-2xl transition-all duration-300 flex items-center justify-between border ${activeIdx === idx
                    ? "bg-zinc-50 border-red-500/30 shadow-lg ring-1 ring-red-500/10"
                    : "bg-white border-zinc-100 hover:border-red-500/10 hover:bg-zinc-50/50"
                    }`}
                >
                  <div className="flex items-center gap-4">
                    <div className={`w-10 h-10 rounded-xl flex items-center justify-center transition-colors ${activeIdx === idx ? "bg-red-100 text-red-600" : "bg-zinc-100 text-zinc-500 group-hover:text-red-600"}`}>
                      {b.icon}
                    </div>
                    <h3 className={`font-bold text-base transition-colors ${activeIdx === idx ? "text-zinc-900" : "text-zinc-700 group-hover:text-zinc-900"}`}>
                      {b.title}
                    </h3>
                  </div>
                  <ArrowRight className={`w-5 h-5 text-red-600 transition-transform ${activeIdx === idx ? "translate-x-0 opacity-100" : "-translate-x-4 opacity-0 group-hover:translate-x-0 group-hover:opacity-50"}`} />
                </button>
              ))}
            </div>

            <div className="w-full lg:w-1/2 min-h-[350px] flex items-center justify-center p-8 bg-zinc-50 border border-zinc-200/60 rounded-3xl relative">
              <div className="max-w-md text-center">
                <div className="w-16 h-16 bg-red-100 text-red-600 rounded-2xl flex items-center justify-center mb-6 mx-auto">
                  {benefits[activeIdx].icon}
                </div>
                <h3 className="text-2xl font-bold text-zinc-900 mb-4">
                  {benefits[activeIdx].title}
                </h3>
                <p className="text-zinc-600 leading-relaxed text-sm" dangerouslySetInnerHTML={{ __html: benefits[activeIdx].desc }} />
              </div>
            </div>
          </div>
        </div>
      </motion.section>

      <CyberSectionDivider theme="red" />

      <DEFCTASection />

      <Footer />
    </main>
  );
}
